name: widgets
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: "3.35.3"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.1
  utils: ^1.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1