name: api
version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: "3.35.5"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.0.1
  firebase_messaging: ^16.0.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  os_detect: ^2.0.3

  utils: ^1.0.0+1
  models: ^1.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0