// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8E4xrZ7nPpBj5Js3Ah7kNaw1liehW7cM',
    appId: '1:799108724870:web:d054b7bf333bc52ae47907',
    messagingSenderId: '799108724870',
    projectId: 'suptrack-c8f9f',
    authDomain: 'suptrack-c8f9f.firebaseapp.com',
    storageBucket: 'suptrack-c8f9f.appspot.com',
    measurementId: 'G-EZ0NNP66PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6nOh_0S6lxJ-JcFW7_O91dOhPygLyD9Y',
    appId: '1:799108724870:android:e35e4e3110df2f35e47907',
    messagingSenderId: '799108724870',
    projectId: 'suptrack-c8f9f',
    storageBucket: 'suptrack-c8f9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVeYz5tEz6xtu_BPBMNZBxZnUw6gzFPgw',
    appId: '1:799108724870:ios:56216bf3197fe6afe47907',
    messagingSenderId: '799108724870',
    projectId: 'suptrack-c8f9f',
    storageBucket: 'suptrack-c8f9f.appspot.com',
    iosBundleId: 'com.svindland.supTrack',
  );
}
