// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgDwkAfomkkflA72nUDOjVGvvCQbsWxYI',
    appId: '1:346843181874:android:500caaf28fe58f07cc9d2b',
    messagingSenderId: '346843181874',
    projectId: 'bptrack-63405',
    storageBucket: 'bptrack-63405.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ4KoJQIj1GkC-g5hicyf0K9lBkjTM3_E',
    appId: '1:346843181874:ios:12ba361e9624ad79cc9d2b',
    messagingSenderId: '346843181874',
    projectId: 'bptrack-63405',
    storageBucket: 'bptrack-63405.appspot.com',
    androidClientId: '346843181874-10a8an4t5c3asbccjo17m19um93hb3e5.apps.googleusercontent.com',
    iosClientId: '346843181874-46mcop9vv562he1rrrp0b4u86tnqoqii.apps.googleusercontent.com',
    iosBundleId: 'com.svindland.bptrack',
  );
}
