// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.fuchsia:
        return null;
      case TargetPlatform.linux:
        return null;
      case TargetPlatform.windows:
        return null;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoPzDTw1lTL56kQkw_WWWcy63vLRCy2X4',
    appId: '1:718751552748:web:0253a98c7fa056c17c41c9',
    messagingSenderId: '718751552748',
    projectId: 'bodytrack-4805f',
    authDomain: 'bodytrack-4805f.firebaseapp.com',
    storageBucket: 'bodytrack-4805f.appspot.com',
    measurementId: 'G-FLMZFXGDBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKgASd8Y-hfbJpWxxvEtnqMQG8Bv8GEhs',
    appId: '1:718751552748:android:0dc0fed7fe7eeef27c41c9',
    messagingSenderId: '718751552748',
    projectId: 'bodytrack-4805f',
    storageBucket: 'bodytrack-4805f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX8ZHKbTDNDSv8mD4SlwCWM05iDNKaPw8',
    appId: '1:718751552748:ios:3f9722224b6f42877c41c9',
    messagingSenderId: '718751552748',
    projectId: 'bodytrack-4805f',
    storageBucket: 'bodytrack-4805f.appspot.com',
    androidClientId: '718751552748-h7vvl5ste38kvge940p3rvduhl23orld.apps.googleusercontent.com',
    iosClientId: '718751552748-p16te2gb0phh8fl7jee7n2vdqj9b281o.apps.googleusercontent.com',
    iosBundleId: 'com.svindland.bodytrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX8ZHKbTDNDSv8mD4SlwCWM05iDNKaPw8',
    appId: '1:718751552748:ios:3f9722224b6f42877c41c9',
    messagingSenderId: '718751552748',
    projectId: 'bodytrack-4805f',
    storageBucket: 'bodytrack-4805f.appspot.com',
    androidClientId: '718751552748-h7vvl5ste38kvge940p3rvduhl23orld.apps.googleusercontent.com',
    iosClientId: '718751552748-p16te2gb0phh8fl7jee7n2vdqj9b281o.apps.googleusercontent.com',
    iosBundleId: 'com.svindland.bodytrack',
  );
}
